# default config
baseurl = "http://gym.leader.glink.blog/"
languageCode = "en-us"
title = "Gym Leader Glink Blog"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 3

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.min.js"

# navigation
[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about"
weight = 2

[[menu.main]]
name = "Contact"
url = "contact"
weight = 3

# deult parameter
[params]
logo = "images/logo.png"
home = "Blog"
# theme layout ( two layout is available, "1" and "2" )
layout = "2"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "Glink"
author_image = "images/test-banner2.png"
bio = "Content Creator ğŸ® Pokemon Trainer ğŸ”´âšªï¸ Fitness Enthusiast ğŸ¥¦ Software Engineer ğŸ‘¨ğŸ»â€ğŸ’» Berlin Based ğŸ“"
# Contact info
mobile = ""
email = "glink.vgc@gmail.com"
address = "Berlin, Germany"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "G-21E0P5YFJE"
# copyright
copyright = "Copyright &copy; 2021 Gym.Leader.Glink"

# Instagram feed
[params.instafeed]
enable = false

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-instagram"
url = "https://www.instagram.com/gym.leader.glink/"

[[params.social]]
icon = "ti-facebook"
url = "https://www.facebook.com/gabriel.cerrato.399/"

[[params.social]]
icon = "ti-twitter-alt"
url = "https://twitter.com/GLinkVGC"

# [[params.social]]
# icon = "ti-github"
# url = "#"
